name: Update version and file list

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  update-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate update-files.json and version.txt
        run: |
          echo "Generating update-files.json and version.txt..."

          file_list=$(find . -maxdepth 1 -type f -name "*.py" \
            ! -name "CONFIG.py" \
            ! -name "WIFI_CONFIG.py" \
            ! -name "CONFIG.example.py" \
            ! -name "WIFI_CONFIG.example.py" \
            -exec basename {} \;)

          file_list=$(printf "%s\nversion.txt" "$file_list")

          echo "$file_list" | jq -R . | jq -s . > update-files.json

          echo "${GITHUB_REF##*/}" > version.txt

          echo "update-files.json contents:"
          cat update-files.json

          echo "version.txt contents:"
          cat version.txt

      - name: Commit and push update
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add update-files.json version.txt
          git commit -m "Update version.txt and update-files.json for ${GITHUB_REF##*/}"
          git push origin HEAD:main
